import CustomHeader from '@/components/CustomHeader/CustomHeader';
import Head from 'next/head';
import { fetchData } from '../../../service/apiService';
// import { useRouter } from 'next/router';
import ResultCard from '../../../components/ResultCard/ResultCard';
import { GetServerSidePropsContext } from 'next';
import { ApiData } from '@/utils/types/types';
import PaginationContainer from '../../../components/PaginationContainer/PaginationContainer';
import SelectItemPerPage from '../../../components/select/SelectItemPerPage';
// import Image from 'next/image';
// import styles from '@/styles/Home.module.css';

const ResultCatalog = ({
  data,
  pageLimit,
  page,
}: {
  data: ApiData;
  pageLimit: string;
  page: string;
}) => {
  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div className="wrap">
        <h1 className="main-title"> Rick and Morty API</h1>
        <div className="main-wrap">
          <CustomHeader />
          {/* {isLoading && <div>Loading...</div>} */}
          {data?.results.length === 0 ? (
            <div>Oops, nothing is found!!!</div>
          ) : (
            <div className="section main-section">
              <h2>Serch results:</h2>
              <PaginationContainer
                cardPerPage={Number(pageLimit)}
                totalCard={data?.total}
                page={page}
              />
              <SelectItemPerPage
                totalCard={pageLimit}
                handleChange={handleChange}
              />
              <ul className="result-list">
                {data?.results.map((item) => (
                  <ResultCard
                    key={item.id}
                    item={item}
                  ></ResultCard>
                ))}
              </ul>
              {/* <Routes>
            <Route
              path="details/:id"
              element={<SideBar />}
            />
          </Routes>
          <Outlet /> */}
            </div>
          )}
        </div>
      </div>
    </>
  );
};

export default ResultCatalog;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const pageUrl = context.params?.page as string;
  const page = pageUrl;
  const pageLimit: string = Array.isArray(context.query.pageLimit)
    ? context.query.pageLimit[0] || '20'
    : context.query.pageLimit || '20';
  const queryParam = context.query['search.name'] as string;

  const data = await fetchData(queryParam, page, pageLimit);

  return {
    props: {
      data,
      pageLimit,
      page: pageUrl,
    },
  };
}
