import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import CustomHeader from '@/components/CustomHeader/CustomHeader';
import ResultCatalog from '@/components/ResultCatalog/ResultCatalog';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div className="wrap">
        <h1 className="main-title"> Rick and Morty API</h1>
        <div className="main-wrap">
          <CustomHeader />
          <ResultCatalog />
        </div>
      </div>
    </>
  );
}
